image: docker:19

services:
  - docker:19-dind


before_script:
  - echo $DH_TOKEN | docker login -u $DH_USER

build:
  stage: build
  script:
    - docker build -t koralowiec/cronbot .
    - docker push koralowiec/cronbot
