image: docker:19

services:
  - docker:19-dind


before_script:
  - echo $DH_TOKEN | docker login -u $DH_USER --password-stdin

build:
  stage: build
  only:
    refs:
      - tags
  script:
    - docker build -t koralowiec/cronbot:$CI_COMMIT_REF_NAME --target base .
    - docker push koralowiec/cronbot:$CI_COMMIT_REF_NAME
    - docker tag koralowiec/cronbot:$CI_COMMIT_REF_NAME koralowiec/cronbot:latest
    - docker push koralowiec/cronbot:latest
