image: docker:19

services:
  - docker:19-dind


before_script:
  - echo $DH_TOKEN | docker login -u $DH_USER --password-stdin

build:
  stage: build
  only:
    refs:
      - master
  script:
    - docker build -t koralowiec/cronbot --target base .
    - docker push koralowiec/cronbot
