version: "2.4"
services:
  bot:
    build:
      context: .
      target: dev
    env_file: 
      - .env
      - .db.env
    volumes:
      - ./src:/bot/src
  pg:
    image: postgres:12.6
    env_file: .db.env
